# Generated by Django 6.0.4 on 2026-04-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='titulo',
        ),
    ]
