# Generated by Django 6.0.4 on 2026-04-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_rename_year_book_ano_rename_author_book_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='ano',
            new_name='year',
        ),
    ]
