# Generated by Django 6.0.4 on 2026-04-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_rename_titulo_book_title_rename_ano_book_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year',
            new_name='ano',
        ),
    ]
