# Generated by Django 6.0.4 on 2026-04-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_rename_year_book_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nivel',
            field=models.CharField(choices=[('CV3', 'CV3'), ('CV4', 'CV4'), ('CV5', 'CV5')], default=2026, max_length=3),
            preserve_default=False,
        ),
    ]
