# Generated by Django 6.0.4 on 2026-05-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('emola', 'e-Mola'), ('mpesa', 'M-Pesa')], default='emola', max_length=20),
        ),
    ]
