# Generated by Django 6.0.4 on 2026-05-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('emola', 'e-Mola'), ('mpesa', 'M-Pesa')], default='mpesa', max_length=20),
        ),
    ]
