# Generated by Django 6.0.4 on 2026-05-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
