# Generated by Django 6.0.4 on 2026-05-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_book_cover_url_book_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
