# Generated by Django 6.0.4 on 2026-05-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_alter_book_pdf'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='book',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
